# embed_languages.cmake
# Scans languages/*.json and generates a C++ header with embedded string data.
# Usage: cmake -DLANG_DIR=... -DOUTPUT_FILE=... -P embed_languages.cmake

file(GLOB LANG_FILES "${LANG_DIR}/*.json")
list(SORT LANG_FILES)

set(OUTPUT "// Auto-generated by embed_languages.cmake — DO NOT EDIT\n")
string(APPEND OUTPUT "#pragma once\n")
string(APPEND OUTPUT "#include <string>\n")
string(APPEND OUTPUT "#include <vector>\n\n")
string(APPEND OUTPUT "struct EmbeddedLang {\n")
string(APPEND OUTPUT "    const char* jsonData;\n")
string(APPEND OUTPUT "};\n\n")
string(APPEND OUTPUT "inline const std::vector<EmbeddedLang>& GetEmbeddedLanguages() {\n")
string(APPEND OUTPUT "    static const std::vector<EmbeddedLang> langs = {\n")

foreach(LANG_FILE ${LANG_FILES})
    file(READ "${LANG_FILE}" FILE_CONTENT)
    # Escape backslashes first, then quotes
    string(REPLACE "\\" "\\\\" FILE_CONTENT "${FILE_CONTENT}")
    string(REPLACE "\"" "\\\"" FILE_CONTENT "${FILE_CONTENT}")
    # Replace real newlines with \n escape sequences
    string(REPLACE "\n" "\\n" FILE_CONTENT "${FILE_CONTENT}")
    string(REPLACE "\r" "" FILE_CONTENT "${FILE_CONTENT}")

    get_filename_component(FNAME "${LANG_FILE}" NAME)
    string(APPEND OUTPUT "        // ${FNAME}\n")
    string(APPEND OUTPUT "        { \"${FILE_CONTENT}\" },\n")
endforeach()

string(APPEND OUTPUT "    };\n")
string(APPEND OUTPUT "    return langs;\n")
string(APPEND OUTPUT "}\n")

file(WRITE "${OUTPUT_FILE}" "${OUTPUT}")
